spring:
  profiles.active: local

---

spring:
  profiles: local
  #配置日志
  logging:
    config: classpath:logback-spring.xml
  #配置数据源
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://39.106.132.4:3306/wx_pub_account?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 20
    min-idle: 2
    validationQuery: select 1
mybatis:
  config-location: classpath:mybatis-config.xml

wx:
  token: wxbestir #用于验证微信访问
  appid: wxf9e94ed2bef6e8e7 #用于获取accessToken
  appsecret: 2bd36932772d3d512a11dffc8aa23967 #用于获取accessToken